<div id="checkout" class="checkout-container">

    <section class="shipping-address">
        <div v-for="field in shippingAddress.field">
            <template v-if="field.type !== 'select'">
                <inputfield 
                    :label="field.label" 
                    :name="field.name" 
                    fieldclass="shipping-address__field"
                    inputclass="input shipping-address__input"
                />
            </template>
            
            <template v-if="field.type === 'select'">
                <selectfield
                    :label="field.label"
                    :name="field.name"
                    fieldclass="shipping-address__field"
                    selectclass="shipping-address__select"
                    :options="field.options"
                />
            </template>
        </div>
    </section>

    <section v-if="step !== 'success'">
        <h1>Totals</h1>
        <pre>{{ config.totalsData }}</pre>
    </section>

    <template v-if="step === 'shipping'">
        <buttonelement
            buttontype="button"
            buttonclass="button"
            text="Set shipping information"
            @click.native="setShippingInformation"
        />
    </template>

    <template v-if="step === 'billing'">
        <buttonelement
            buttontype="button"
            buttonclass="button"
            text="Back"
            @click.native="step = 'shipping'"
        />
    </template>

    <template v-if="step === 'billing'">
        <buttonelement
            buttontype="button"
            buttonclass="button"
            text="Make Order"
            @click.native="makeOrder"
        />
    </template>

    <template v-if="step === 'success'">
        We did it!
        <a href="/what-is-new.html">
            Back to category
        </a>
    </template>
</div>

<script>
    require([
        'vue', 
        'Snowdog_VueCheckout/js/components/input.babel',
        'Snowdog_VueCheckout/js/components/select.babel',
        'Snowdog_VueCheckout/js/components/button.babel',
        'Snowdog_VueCheckout/js/lib/babel.min'
    ], function(
        Vue, 
        inputComponent, 
        selectComponent, 
        buttonComponent, 
        es6
    ) {
        new inputComponent();
        new selectComponent();
        new buttonComponent();

        var app = new Vue({
            el: '#checkout',
            data: {
                baseUrl: '<?= $block->getBaseUrl() ?>',
                layout: <?= $block->getJsLayout() ?>,
                config: <?= \Zend_Json::encode($block->getCheckoutConfig()) ?>,
                shippingAddress: {},
                billingAddress: {},
                step: 'shipping'
            },
            computed: {
                cartId() {
                    return this.config.quoteData.entity_id
                },
                cart() {
                    const cart = this.config.quoteData;
                    cart.items = this.config.quoteItemData;
                    return cart;
                },
                countryList() {
                    return this.layout.checkout.checkoutProvider.dictionaries.country_id
                },
                regionList() {
                    return this.layout.checkout.checkoutProvider.dictionaries.region_id
                }
            },
            methods: {
                parseJSON: function (response) {
                    return new Promise(
                        (resolve) => response.json()
                            .then((json) => resolve({
                                status: response.status,
                                ok: response.ok,
                                json
                            }))
                    )
                },
                request: function (url, params = {}) {
                    return new Promise((resolve, reject) => {
                        fetch(url, params)
                            .then(this.parseJSON)
                            .then((response) => {
                                if (response.ok) {
                                    return resolve(response.json)
                                }
                                // extract the error from the server's json
                                return reject(response.json)
                            })
                            .catch((error) => reject({
                                networkError: error.message
                            }));
                    })
                },
                prepareShippingAddress() {
                    const addressFields = this.layout
                            .components
                            .checkout
                            .children
                            .steps
                            .children
                            ['shipping-step']
                            .children
                            .shippingAddress
                            .children
                            ['shipping-address-fieldset']
                            .children;

                    this.shippingAddress.field = [];

                    Object.keys(addressFields).forEach(id => {
                        const field = addressFields[id];
                        if (field.config) {
                            if (field.children) {
                                field.children.forEach(child => {
                                    this.shippingAddress.field.push({
                                        type: child.config.elementTmpl.replace(/^.*\/(.*)$/, "$1"),
                                        name: `${id}[${child.dataScope}]`,
                                        label: field.label
                                    })
                                })
                            }
                            else {
                                this.shippingAddress.field.push({
                                    type: field.config.elementTmpl.replace(/^.*\/(.*)$/, "$1"),
                                    name: id,
                                    label: field.label,
                                    options: [
                                        {
                                            'value': 'option1', 
                                            'text': 'Option One'
                                        },
                                        {
                                            'value': 'option2', 
                                            'text': 'Option Two'
                                        }
                                    ]
                                })
                            }
                        }
                        else {
                            this.shippingAddress[id] = field;
                        }
                    });
                },
                setShippingInformation() {
                    this.request(
                        `${this.baseUrl}index.php/rest/V1/guest-carts/${this.cartId}/shipping-information`,
                        {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json'
                            },
                            body: JSON.stringify({
                                "addressInformation": {
                                    "shipping_address": {
                                        "region": "string",
                                        "region_id": 0,
                                        "region_code": "string",
                                        "country_id": "PL",
                                        "street": [
                                            "string"
                                        ],
                                        "company": "string",
                                        "telephone": "string",
                                        "fax": "string",
                                        "postcode": "string",
                                        "city": "string",
                                        "firstname": "string",
                                        "lastname": "string",
                                        "middlename": "string",
                                        "prefix": "string",
                                        "suffix": "string",
                                        "vat_id": "string",
                                        "customer_id": 0,
                                        "email": "test@test.com",
                                        "same_as_billing": 0,
                                        "customer_address_id": 0,
                                        "save_in_address_book": 0,
                                        "custom_attributes": [
                                            {
                                                "attribute_code": "string",
                                                "value": "string"
                                            }
                                        ]
                                    },
                                    "billing_address": {
                                        "region": "string",
                                        "region_id": 0,
                                        "region_code": "string",
                                        "country_id": "PL",
                                        "street": [
                                            "string"
                                        ],
                                        "company": "string",
                                        "telephone": "string",
                                        "fax": "string",
                                        "postcode": "string",
                                        "city": "string",
                                        "firstname": "string",
                                        "lastname": "string",
                                        "middlename": "string",
                                        "prefix": "string",
                                        "suffix": "string",
                                        "vat_id": "string",
                                        "customer_id": 0,
                                        "email": "test@test.com",
                                        "same_as_billing": 0,
                                        "customer_address_id": 0,
                                        "save_in_address_book": 0,
                                        "custom_attributes": [
                                            {
                                                "attribute_code": "string",
                                                "value": "string"
                                            }
                                        ]
                                    },
                                    "shipping_method_code": "flatrate",
                                    "shipping_carrier_code": "flatrate",
                                    "extension_attributes": {},
                                    "custom_attributes": [
                                        {
                                            "attribute_code": "string",
                                            "value": "string"
                                        }
                                    ]
                                }
                            })
                        }
                    )
                        .then(response => {
                            this.config.paymentMethods = response.payment_methods;
                            this.config.totalsData = response.totals;
                            this.step = 'billing';
                        });
                },
                makeOrder() {
                    this.request(
                        `${this.baseUrl}index.php/rest/V1/guest-carts/${this.cartId}/order`,
                        {
                            method: 'PUT',
                            headers: {
                                'Content-Type': 'application/json'
                            },
                            body: JSON.stringify({
                                "paymentMethod": {
                                    "po_number": "string",
                                    "method": "checkmo",
                                    "additional_data": [
                                        "string"
                                    ],
                                    "extension_attributes": {
                                        "agreement_ids": [
                                            "string"
                                        ]
                                    }
                                }
                            })
                        }
                    )
                        .then(response => {
                            this.step = 'success';
                        })
                }
            },
            created() {
                this.prepareShippingAddress()
            }
        })
    });
</script>