<script>
    var billingAddress = [
        {
            "type": "email",
            "name": "email",
            "label": "Email",
            "requried": "",
            "placeholder": "",
            "value": "",
            "order": 0,
            "disabled": ""
        },
        {
            "type": "text",
            "name": "firstname",
            "label": "First Name",
            "requried": "",
            "placeholder": "",
            "value": "",
            "order": 10,
            "disabled": ""
        },
        {
            "type": "text",
            "name": "lastname",
            "label": "Last Name",
            "requried": "",
            "placeholder": "",
            "value": "",
            "order": 20,
            "disabled": ""
        },
        {
            "type": "tel",
            "name": "telephone",
            "label": "Phone Number",
            "requried": "",
            "placeholder": "",
            "value": "",
            "order": 30,
            "disabled": ""
        },
        {
            "type": "text",
            "name": "street[0]",
            "label": "Street Address",
            "requried": "",
            "placeholder": "",
            "value": "",
            "order": 40,
            "disabled": ""
        },
        {
            "type": "text",
            "name": "street[1]",
            "label": "Street Address",
            "requried": "",
            "placeholder": "",
            "value": "",
            "order": 50,
            "disabled": ""
        },
        {
            "type": "select",
            "name": "country_id",
            "label": "Country",
            "requried": "",
            "placeholder": "",
            "value": "",
            "order": 60,
            "disabled": "",
            "options": countryList
        },
        {
            "type": "text",
            "name": "city",
            "label": "City",
            "requried": "",
            "placeholder": "",
            "value": "",
            "order": 70,
            "disabled": ""
        },
        {
            "type": "text",
            "name": "postcode",
            "label": "Zip/Postal Code",
            "requried": "",
            "placeholder": "",
            "value": "",
            "order": 80,
            "disabled": ""
        },
        {
            "type": "select",
            "name": "region_id",
            "label": "State/Province",
            "requried": "",
            "order": 90,
            "disabled": "",
            "options": regionList
        },
        {
            "type": "text",
            "name": "company",
            "label": "Company",
            "requried": "",
            "placeholder": "",
            "value": "",
            "order": 100,
            "disabled": ""
        }
    ];

</script>
