<script>
    var shippingInformation = {
        "addressInformation": {
            "shipping_address": {
                "region": "string",
                "region_id": 0,
                "region_code": "string",
                "country_id": "PL",
                "street": [
                    "string"
                ],
                "company": "string",
                "telephone": "string",
                "fax": "string",
                "postcode": "string",
                "city": "string",
                "firstname": "string",
                "lastname": "string",
                "middlename": "string",
                "prefix": "string",
                "suffix": "string",
                "vat_id": "string",
                "customer_id": 0,
                "email": "test@test.com",
                "same_as_billing": 0,
                "customer_address_id": 0,
                "save_in_address_book": 0,
                "custom_attributes": [{
                    "attribute_code": "string",
                    "value": "string"
                }]
            },
            "billing_address": {
                "region": "string",
                "region_id": 0,
                "region_code": "string",
                "country_id": "PL",
                "street": [
                    "string"
                ],
                "company": "string",
                "telephone": "string",
                "fax": "string",
                "postcode": "string",
                "city": "string",
                "firstname": "string",
                "lastname": "string",
                "middlename": "string",
                "prefix": "string",
                "suffix": "string",
                "vat_id": "string",
                "customer_id": 0,
                "email": "test@test.com",
                "same_as_billing": 0,
                "customer_address_id": 0,
                "save_in_address_book": 0,
                "custom_attributes": [{
                    "attribute_code": "string",
                    "value": "string"
                }]
            },
            "shipping_method_code": "flatrate",
            "shipping_carrier_code": "flatrate",
            "extension_attributes": {},
            "custom_attributes": [{
                "attribute_code": "string",
                "value": "string"
            }]
        }
    };
</script>
